version: "0.3"

jobs:
  - name: generate-jobs
    type: exec
    steps:
      - name: compile
        commands: |
          . build/scripts/lib/go-env.sh        
          cd build && go build -mod=vendor -o "${GOBIN}/dynamic-build" .
      - name: execute
        commands: |
          . build/scripts/lib/go-env.sh
          "${GOBIN}/dynamic-build"
