version: "0.2"

jobs:
  - name: generate-jobs
    docker:
      image: golang:1.19.7
      pull: if-not-exists
      shell: /bin/bash
    steps:
      - name: compile
        commands: |
          . build/scripts/lib/go-env.sh        
          cd build && go build -mod=vendor -o "${GOBIN}/dynamic-build" .
      - name: execute
        commands: |
          . build/scripts/lib/go-env.sh
          "${GOBIN}/dynamic-build"
