name: Build BuildBeaver CLI

on: 
  workflow_dispatch:
  push:
    tags: ["v**"]

env:
  GOPATH: ${{ github.workspace }}
  GOBIN: ${{ github.workspace }}/bin

defaults:
  run:
    working-directory: backend

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18.10
        cache-dependency-path: backend/go.sum

    - name: Install wire
      run: go install github.com/google/wire/cmd/wire@v0.5.0

    - name: Run wire
      run: make generate-wire

    - name: Run tests
      run: make test

    - name: Build
      run: make build

    # See https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
    - name: Tar files for upload
      run: |
        filename=$(echo "bb_${{github.ref_name}}_${{runner.os}}_${{runner.arch}}" | tr '[:upper:]' '[:lower:]')
        replaced_filename=${filename/"macos"/"osx"}
        tar -czvf ${replaced_filename}.tar.gz -C ${{ env.GOBIN }}/ bb
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: bb_${{github.ref_name}}_${{runner.os}}_${{runner.arch}}
        path: backend/*.tar.gz
        if-no-files-found: error